---
name: Security
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trufflehog:
    name: trufflehog
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout source code

    - name: Running trufflehog
      uses: UnicornGlobal/trufflehog-actions-scan@master
